# Generated by Django 4.0 on 2021-12-31 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_endereco_cep_alter_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('tipo_funcionario', models.IntegerField(choices=[(1, 'Atendente'), (2, 'Médico')])),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.endereco')),
            ],
        ),
    ]
